### ISSUE TITLE
How to active scripts or test it with real network call?

### ISSUE THREAD

**Issue by hprobotic** [iSteal-it/script#1]
Hey, thank you for your hard work on this. can you please add some instruction about how to use?

**Comment by iSteal-it** [comment]
You can follow this video https://youtu.be/fYsOcbVp3IA
On how to use script

**Comment by hprobotic** [comment]
Hi thank you @iSteal-it. My question is not about how to use script. I just asking about how we can debug the script with real network request.

RIght now when i try to run script. that's calling to https://example.com and response is hello

**Comment by iSteal-it** [comment]
The json files are the response 
Request is made by app api
Like picart app says give subscription info 
In return it gives picart.json

**Comment by BlackYukiDTD** [comment]
how to find the api (host name) address. Can you let me know

**Comment by hprobotic** [comment]
> how to find the api (host name) address. Can you let me know

You need to use charlies or mitmproxy for that

**Comment by iSteal-it** [comment]
Completed
